### ISSUE TITLE
Should we try to clarify intent of Rust adoption at companies?

### ISSUE THREAD

**Issue by rylev** [rust-lang/surveys#217]
As pointed out [here](https://rust-lang.zulipchat.com/#narrow/stream/217588-project-leads-.28public.29/topic/2022.20Annual.20Survey/near/306327506), tn the "To what extent is Rust currently being used by your company?" question, it may be useful to provide different options for "Rust is being used as a deliberate and strategic decision at my company" versus "Rust is being used incidentally at my company".

**Comment by apiraino** [comment]
Personally, I find it a bit hard to fully get what this distinction is intended to convey.

What does "Rust is being used incidentally at my company" actually mean? That my devs use `ripgrep` instead of GNU grep? Or that we use `axum` instead of `express` because the local [RESF](https://enet4.github.io/rust-tropes/rust-evangelism-strike-force/) is vocal about it?

I wil close this as not sufficiently actionable as it is formulated.  I'll link this suggestion to #188 because there *is* a nugget of interesting question we can ask the community
